version: '3'

services:

  protocol-db:
    container_name: protocol-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    build:
      context: ./database
      dockerfile: Dockerfile
    networks:
      - ondc-api-network
    volumes:
      - protocol_network_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
            "CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  protocol-network-api:
    build:
      context: .
      dockerfile: ./app/Dockerfile    
    container_name: protocol-network-api
    depends_on:
      - protocol-db
    environment:
      - POSTGRES_HOST=protocol-db
    networks:
      - ondc-api-network
    env_file:
      - .env
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "5678:5678"

networks:
  ondc-api-network:
    driver: bridge
volumes:
  protocol_network_data:

